services:
    trusted-output:
        env_file: .env
        container_name: trusted-output
        environment:
            CI: $CI
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/app/src
        restart: always
        networks:
            - trusted-output
        ports:
            - 2345:2345
networks:
    trusted-output:
volumes:
    node_modules:
