services:
    trusted-output:
        env_file: .env
        container_name: trusted-output
        environment:
            CI: $CI
            MANAGEMENT_APP_PUBLIC_KEY: |
                -----BEGIN PUBLIC KEY-----
                -----END PUBLIC KEY-----

            MANAGEMENT_APP_PRIVATE_KEY: |
                -----BEGIN PUBLIC KEY-----
                -----END PUBLIC KEY-----

        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/app/src
        restart: always
        networks:
            - trusted-output
        ports:
            - 2345:2345
        command: /bin/sh
networks:
    trusted-output:
volumes:
    node_modules:
