services:
    trusted-output-app:
        container_name: trusted-output-app
        environment:
            - CI=$CI
# Will we need clerk post-pilot?
#            - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
#            - CLERK_SECRET_KEY=$CLERK_SECRET_KEY
#            - E2E_CLERK_USER_USERNAME=$E2E_CLERK_USER_USERNAME
#            - E2E_CLERK_USER_PASSWORD=$E2E_CLERK_USER_PASSWORD
            - MANAGEMENT_APP_API_URL=TODO_FIGURE_ME_OUT
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./:/app/
            - node_modules:/app/node_modules
        restart: always
        networks:
            - mgmnt-app
        ports:
            - 3000:3000
        healthcheck:
            test: ['CMD-SHELL', 'curl -s http://localhost:3000/']
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
networks:
    mgmnt-app:
volumes:
    pgdata:
    node_modules:
