FROM node:21-bookworm AS base

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

RUN npx playwright install
RUN npx playwright install-deps

ENV NEXT_TELEMETRY_DISABLED=1

CMD ["npm", "run", "dev"]
