services:
    trusted-output:
        container_name: trusted-output
        # TODO Probably don't need clerk stuff in here
        environment:
            - CI=$CI
            - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            - CLERK_SECRET_KEY=$CLERK_SECRET_KEY
            - E2E_CLERK_USER_USERNAME=$E2E_CLERK_USER_USERNAME
            - E2E_CLERK_USER_PASSWORD=$E2E_CLERK_USER_PASSWORD
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app/
            - node_modules:/app/node_modules
        restart: always
        networks:
            - trusted-output
        ports:
            - 3000:3000
        healthcheck:
            test: ['CMD-SHELL', 'curl -s http://localhost:3000/']
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
networks:
    trusted-output:
volumes:
    node_modules:
