services:
    trusted-output:
        container_name: trusted-output
        environment:
            - CI=$CI
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app/
            - node_modules:/app/node_modules
        restart: always
        networks:
            - trusted-output
        ports:
            - 3000:3000
networks:
    trusted-output:
volumes:
    node_modules:
