services:
    trusted-output:
        container_name: trusted-output
        environment:
            - CI=$CI
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app/
            - node_modules:/app/node_modules
        restart: always
        networks:
            - trusted-output
        ports:
            - 3000:3000
        healthcheck:
            test: ['CMD-SHELL', 'curl -s http://localhost:3000/']
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
networks:
    trusted-output:
volumes:
    node_modules:
